### PR TITLE
Fix issues 2464.

### PR DESCRIPTION
**Pull request by jizhidejingmo**
解决[config registerMethods];方法缺失

### CODE REVIEW

**Comment by acton393** [comment]
hi @jizhidejingmo please sign the CLA when you commit your first pull request.

It seems your commit GitHub id is not the same as your comment's.

**Comment by jizhidejingmo** [comment]
OK, CLA已经签过了

**Comment by acton393** [comment]
Hi,  it seems that you commit code using GitHub id  called `杨洋` which doesn't signed the CLA, but  your  commit id `jizhidejingmo` signed,   so  the CLA checked the commit id called `杨洋`didn't signed yet.

You can use 'git config user.email '  and 'git config user.name' to config your commit user account.

**Comment by jizhidejingmo** [comment]
OK，修改过了

**Comment by acton393** [comment]
hi @jizhidejingmo  thx for your contribution ~~

**Pull request merged**
