### PR TITLE
* [android] add timeout config and put/delete/head/patch method to fetch

### PR DESCRIPTION
**Pull request by denghongcai**
0. add timeout option to fetch options
0. add PUT/DELETE/HEAD/PATCH method support

### CODE REVIEW

**Comment by luics** [comment]
hi @denghongcai , I don't find any android code? 
and pls don't submit embeded js

**Comment by denghongcai** [comment]
@luics it did contain android code, Github has problem when changes is huge.
Contributor Guide never told us what file shouldn't be submit, I just follow the `.gitignore`.

**Comment by luics** [comment]
@denghongcai thx for the pr, pls resubmit anthoer pr.

**Comment by denghongcai** [comment]
@luics just resubmit the current commit or need some modify?

**Comment by luics** [comment]
@denghongcai pls resubmit just android code.

**Pull request closed without merging**
