### PR TITLE
[ios] image component 支持预览相册图片解决方案

### PR DESCRIPTION
**Pull request by HJ-StevenSun**
公司在weex 项目中类似发送朋友圈的功能界面需要获得预览相册图片的功能，达到的效果如图

我在看了playground 的代码以后image 标签是通过 WXImageComponent.h 这个组件创建imageView 而得来的，在显示图片的方法中目前只支持了从网络中获取图片的方法，我在这个 方法中对imageSrc这个参数进行了一个判断，判断他是网络图片还是沙盒本地图片如果是沙盒本地图片就取出沙盒本地图片，else 的就去取网络图片。我这样子的做自己觉得法会显得雍肿，因为每次预览完以后我需要将沙盒的图片重新删除一次。
所以希望大家一起来优化一下，Weex 官方也可以拿出更好的解决办法！
`- (void)updateImage
{
    __weak typeof(self) weakSelf = self;
    dispatch_async(WXImageUpdateQueue, ^{
        [self cancelImage];
        
        if (CGRectEqualToRect(self.calculatedFrame, CGRectZero)) {
            return;
        }
        void(^downloadFailed)(NSString *, NSError *) = ^void(NSString *url, NSError *error){
            WXLogError(@"Error downloading image:%@, detail:%@", url, [error localizedDescription]);
        };
        NSString *imageSrc = weakSelf.imageSrc;
        NSString *placeholderSrc = weakSelf.placeholdSrc;
        
        if (weakSelf.placeholdSrc) {
            WXLogDebug(@"Updating image, component:%@, placeholder:%@ ", self.ref, placeholderSrc);
            weakSelf.placeholderOperation = [[weakSelf imageLoader] downloadImageWithURL:placeholderSrc imageFrame:weakSelf.calculatedFrame userInfo:nil completed:^(UIImage *image, NSError *error, BOOL finished) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    __strong typeof(self) strongSelf = weakSelf;
                    UIImage *viewImage = ((UIImageView *)strongSelf.view).image;
                    if (error) {
                        downloadFailed(placeholderSrc,error);
                        if ([strongSelf isViewLoaded] && !viewImage) {
                            ((UIImageView *)(strongSelf.view)).image = nil;
                        }
                        return;
                    }
                    if (![placeholderSrc isEqualToString:strongSelf.placeholdSrc]) {
                        return;
                    }
                   
                    if ([strongSelf isViewLoaded] && !viewImage) {
                        ((UIImageView *)strongSelf.view).image = image;
                    }
                });
            }];
        }
            dispatch_async(dispatch_get_main_queue(), ^{
                weakSelf.imageOperation = [[weakSelf imageLoader] downloadImageWithURL:imageSrc imageFrame:weakSelf.calculatedFrame userInfo:userInfo completed:^(UIImage *image, NSError *error, BOOL finished) {
                    dispatch_async(dispatch_get_main_queue(), ^{
                        __strong typeof(self) strongSelf = weakSelf;
                        
                        if (weakSelf.imageLoadEvent) {
                            [strongSelf fireEvent:@"load" params:@{ @"success": error? @"false" : @"true"}];
                        }
                        if (error) {
                            downloadFailed(imageSrc, error);
                            return ;
                        }
                        
                        if (![imageSrc isEqualToString:strongSelf.imageSrc]) {
                            return ;
                        }
                        
                        if ([strongSelf isViewLoaded]) {
                            ((UIImageView *)strongSelf.view).image = image;
                        }
                    });
                }];
            });
        }
        if (!weakSelf.imageSrc && !weakSelf.placeholdSrc) {
            dispatch_async(dispatch_get_main_queue(), ^{
                self.layer.contents = nil;
            });
        }
    });
}`
以下是我修改过以后的方法
`- (void)updateImage
{
    __weak typeof(self) weakSelf = self;
    dispatch_async(WXImageUpdateQueue, ^{
        [self cancelImage];
        
        if (CGRectEqualToRect(self.calculatedFrame, CGRectZero)) {
            return;
        }
        
        void(^downloadFailed)(NSString *, NSError *) = ^void(NSString *url, NSError *error){
            WXLogError(@"Error downloading image:%@, detail:%@", url, [error localizedDescription]);
        };
        
        NSString *imageSrc = weakSelf.imageSrc;
        NSString *placeholderSrc = weakSelf.placeholdSrc;
        
        if (weakSelf.placeholdSrc) {
            WXLogDebug(@"Updating image, component:%@, placeholder:%@ ", self.ref, placeholderSrc);
            weakSelf.placeholderOperation = [[weakSelf imageLoader] downloadImageWithURL:placeholderSrc imageFrame:weakSelf.calculatedFrame userInfo:nil completed:^(UIImage *image, NSError *error, BOOL finished) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    __strong typeof(self) strongSelf = weakSelf;
                    UIImage *viewImage = ((UIImageView *)strongSelf.view).image;
                    if (error) {
                        downloadFailed(placeholderSrc,error);
                        if ([strongSelf isViewLoaded] && !viewImage) {
                            ((UIImageView *)(strongSelf.view)).image = nil;
                        }
                        return;
                    }
                    if (![placeholderSrc isEqualToString:strongSelf.placeholdSrc]) {
                        return;
                    }
                   
                    if ([strongSelf isViewLoaded] && !viewImage) {
                        ((UIImageView *)strongSelf.view).image = image;
                    }
                });
            }];
        }
        if (weakSelf.imageSrc) {
            NSDictionary *userInfo = @{@"imageQuality":@(weakSelf.imageQuality), @"imageSharp":@(weakSelf.imageSharp)};
            
            if ([weakSelf.imageSrc rangeOfString:@"/Users/"].location !=NSNotFound ||
                [weakSelf.imageSrc rangeOfString:@"/var/"].location !=NSNotFound)
            {
                NSLog(@"读取沙盒图片");
                dispatch_async(dispatch_get_main_queue(), ^{
                    
                    
                __strong typeof(self) strongSelf = weakSelf;
                    
                UIImage *img = [[UIImage alloc]initWithContentsOfFile:weakSelf.imageSrc];
                ((UIImageView *)strongSelf.view).image = img;
                    
                });

            }
            else{
            dispatch_async(dispatch_get_main_queue(), ^{
                weakSelf.imageOperation = [[weakSelf imageLoader] downloadImageWithURL:imageSrc imageFrame:weakSelf.calculatedFrame userInfo:userInfo completed:^(UIImage *image, NSError *error, BOOL finished) {
                    dispatch_async(dispatch_get_main_queue(), ^{
                        __strong typeof(self) strongSelf = weakSelf;
                        
                        if (weakSelf.imageLoadEvent) {
                            [strongSelf fireEvent:@"load" params:@{ @"success": error? @"false" : @"true"}];
                        }
                        if (error) {
                            downloadFailed(imageSrc, error);
                            return ;
                        }
                        
                        if (![imageSrc isEqualToString:strongSelf.imageSrc]) {
                            return ;
                        }
                        
                        if ([strongSelf isViewLoaded]) {
                            ((UIImageView *)strongSelf.view).image = image;
                        }
                    });
                }];
            });
        }
        }
        
        if (!weakSelf.imageSrc && !weakSelf.placeholdSrc) {
            dispatch_async(dispatch_get_main_queue(), ^{
                self.layer.contents = nil;
            });
        }
            
    });
}`
关于我这个判断的地方我觉得还有点不对的地方，因为网络连接的图片如果包含了 /var/ 或者/User/这个 字节的时候就会出错，这是我临时的解决方案

### CODE REVIEW

**Comment by kfeagle** [comment]
rangeOfString  可以换成 hasPrefix

**Comment by cxfeng1** [comment]
@HJ-StevenSun  先rebase一下

**Comment by HJ-StevenSun** [comment]
@cxfeng1  等我 晚上 回去  弄

**Comment by HJ-StevenSun** [comment]
@kfeagle  OK thks

**Comment by cxfeng1** [comment]
这个暂时先关掉了， 请先rebase好再提交， 谢谢

**Pull request closed without merging**
