### PR TITLE
* [android] optimize code and to make more readable

### PR DESCRIPTION
**Pull request by LeeJay0226**
1. remove redundant members(children, parent) that in class WXDomObject.
2. modify functions' decoration, such add final.
3. change fixedStyleRefs into WXDomStatement(because that was only used on root WXDomObject), and optimize function #rebuildingDomTree.
4. make function #transformStyle simply.

### CODE REVIEW

**Comment by sospartan** [comment]
@YorkShen 请通盘考虑修改的影响,如果对逻辑有影响,可以建议对修改进行调整,不要过于发散.

**Comment by YorkShen** [comment]
@LeeJay0226 This PR is conflicts with dev branch. Please fix it. 

Besides, this PR will also be conflict with https://github.com/sospartan/weex/pull/10

**Comment by sospartan** [comment]
@LeeJay0226 @YorkShen v0.7发布后再重新发吧

**Comment by LeeJay0226** [comment]
ok，后面我提到dev 的0.7分支上

**Pull request closed without merging**
