### PR TITLE
Update display-logic.md

### PR DESCRIPTION
**Pull request by you-you**
"Every item in an array is also a **structed** data" has error,should be "Every item in an array is also a **structured** data".

### CODE REVIEW

**Comment by lvscar** [comment]
thx @you-you  ,  you can directly submit PR to  **doc branch**  that have the ablility to auto deployment.

**Comment by luics** [comment]
pls re-commit to doc branch

**Comment by you-you** [comment]
OK,I will do.

**Comment by you-you** [comment]
OK,I will do.@lvscar

**Pull request merged**
