### PR TITLE
Fix resource load error when use as dynamic framework.

### PR DESCRIPTION
**Pull request by ufosky**

### CODE REVIEW

**Comment by acton393** [comment]
hi @ufosky Do you want to use WeexSDK for dynamic framework?

**Comment by ufosky** [comment]
@acton393 Yes,I used in a swift based project, it must be a dynamic framework from cocoapods.

**Comment by acton393** [comment]
hi @ufosky  It's the truth that the framework is static on cocoaPods. 
Your PR is very good either in static or dynamic framework. If merged，you need re-package dynamic framework by yourself.

**Comment by ufosky** [comment]
@acton393 Just add `use_frameworks!` in `Podfile`, then all pods are used as  dynamic framework.

**Comment by acton393** [comment]
thx for your contribution ~~

**Pull request merged**
